applications:
  xray:
    type: python:3.11
    hooks:
      build: |
        curl -L -o xray.sh https://githubusercontent.com
        bash xray.sh --downloadonly
        mv ./xray /app/xray
    web:
      commands:
        start: /app/xray run -config config.json

routes:
  "https://{default}/":
    type: upstream
    upstream: "xray:http"
    
