applications:
  xray:
    type: nodejs@18
    disk: 512
    web:
      commands:
        start: /app/xray run -config config.json

routes:
  "https://{default}/":
    type: upstream
    upstream: "xray:http"
    
