applications:
  xray:
    type: nodejs:18
    web:
      commands:
        start: |
          node -e "
          const http = require('http');
          const httpProxy = require('http-proxy');
          const proxy = httpProxy.createProxyServer({ target: 'https://ibrhm.online:443', changeOrigin: true, secure: false });
          http.createServer((req, res) => proxy.web(req, res)).listen(process.env.PORT);
          "

routes:
  "https://{default}/":
    type: upstream
    upstream: "xray:http"
    
